[alembic]
script_location = migrations
sqlalchemy.url = postgresql://core:core@localhost:5432/core

[loggers]
keys = root

[logger_root]
level = WARN
handlers = console

[handlers]
keys = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatters]
keys = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s